[package]
# Semantic Versioning is used: https://semver.org/
version = "0.1.0"

# Description
title =  "Isaac Lab Dynamics"
description="Extension containing useful tools for control and modelling"
readme  = "docs/README.md"
repository = "https://github.com/andregonz/IsaacDynamics"
category = "robotics"
keywords = ["dynamics", "robotics", "control", "isaaclab"]

[dependencies]
"isaaclab" = {}

[core]
reloadable = false

# Main python module this extension provides.
[[python.module]]
name = "isaaclab_dynamics"
